language: node_js
node_js:
- '8.8.1'

before_install: npm install -g grunt-cli

cache:
  directories:
    - node_modules
    - .python
install: npm install

before_script: npm run build:tests

script: npm run test
