language: node_js
node_js:
- '0.10'
before_install: npm install -g grunt-cli
install: npm install
notifications:
  slack:
    secure: ifd6a2cATNMMDzNl6rsHTpNRhxMa8mes3qrj3lBkv9VzmjN/WaQToOjvQS03//njtYGhq5IHIKAvFg4/6uhRnSWDJIgWvFWz3tB719EOBzNCw6+H6IypWI/Ofl7yr3HuwtofJEuUmOfF6HgxxEU3Oi46HmDTgzIJynPLy6+VcXg=
