
name: CI

on: [push]

jobs:

  build:
    runs-on: ${{matrix.os}}
    name: ${{matrix.os}}, Node ${{matrix.node}}
    strategy:
      fail-fast: false
      matrix:
        os: [macOS-latest, ubuntu-latest, windows-latest]
        node: [16]

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: 'pipenv'

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.3.0
        with:
          node-version: ${{matrix.node}}
          cache: 'npm'

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # caching node_modules
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install NPM Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Linting and Unit testing
        run: |
          npm test

      - name: Build the application
        run: |
          npm run build:ci

      - name: Run E2E tests - Chrome / MacOS
        if: ${{ runner.os == 'macOS' }}
        run: |
          npm run start &
          sleep 10
          npm run e2e:headless:chrome:localStorageDisabled
          npm run e2e:headless:chrome

      - name: Run E2E tests - Firefox / Windows
        if: ${{ runner.os == 'Windows' }}
        run: |
          npm run start &
          sleep 10
          npm run e2e:headless:firefox:localStorageDisabled
          npm run e2e:headless:firefox


