name: Secret Check
# https://github.com/zricethezav/gitleaks
  
on: [push]

jobs:
  secret-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: gitleaks-action
        uses: eshork/gitleaks-action@v1.0.0
